version: "3.8"

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/flaskdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  # Host's port 3308 maps to container's port 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
