version: "3.8"

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development # need it on flask.
      - MYSQL_HOST=db          # Host name of the MySQL service
      - MYSQL_USER=user        # User for Flask to connect to the database
      - MYSQL_PASSWORD=1234    # Password for the user
      - MYSQL_DATABASE=flaskdb # Database name
    depends_on:
      - db
    networks:
      - flask-network

  db:
    image: mysql:5.7  # Downgrade to MySQL 5.7
    environment: # must use first 2 environment variables.
      - MYSQL_USER=user        # User for MySQL setup 
      - MYSQL_PASSWORD=1234    # Password for the user
      - MYSQL_DATABASE=flaskdb # Database name to initialize
      - MYSQL_ROOT_PASSWORD=1234 # Root password for MySQL
    ports:
      - "3308:3306"  # Host's port 3308 maps to container's port 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Mount the init.sql file
    networks:
      - flask-network

networks:
  flask-network:

volumes:
  db_data: